#!/usr/bin/env bash
# Find project deploy directory and run deploy tasks in there
# Extra args are packaged into MHD_ARGS env var to be parsed by the task runner

set -e
ancestor_dir=$(git rev-parse --show-toplevel)
project_dir=${ancestor_dir%%-control}
cd "${project_dir}/deploy" >/dev/null

vault_opts=""
mhd_args=""
task_args=""
if [[ $# == 0 ]]; then
  task_args=""
elif [[ $1 =~ ^--.* ]]; then
  task_args="$*"
else
  task_args="$1"
  shift
  IFS=$'\t'
  mhd_args="$*"
fi
if [[ $task_args =~ ^open:.* ]]; then
  vault_opts="--duration=1h"
fi

if [[ -f gulpfile.ts ]]; then
  # TypeScript deploy: gulp tasks in gulpfile.ts
  [[ -z $task_args ]] && task_args="--tasks --compact-tasks"
  runner=(env TS_NODE_TRANSPILE_ONLY=true node_modules/.bin/gulp)
else
  # Python deploy: uv + typer tasks in tasks.py
  [[ -z $task_args ]] && task_args="--help"
  runner=(uv run tasks.py)
fi

if [ "$CI" = "true" ]; then
  # shellcheck disable=SC2086
  MHD_ARGS="$mhd_args" "${runner[@]}" $task_args
else
  # shellcheck disable=SC2086
  MHD_ARGS="$mhd_args" aws-vault exec $vault_opts mindhive-ops -- "${runner[@]}" $task_args
fi
